name: Test Auction Arbitrage Bot

on: [push]

jobs:
  test:
    name: python test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Compile protobuf
        run: nix develop --command make proto
      - name: Lint
        run: nix develop --command make lint
      - name: Run tests
        run: nix develop --command make test
        
